# Generated by Django 4.1.1 on 2022-12-03 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('charge', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('connection_time', models.CharField(max_length=5)),
                ('disconnection_time', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('charge', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('connection_time', models.CharField(max_length=5)),
                ('disconnection_time', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('charge', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('connection_time', models.CharField(max_length=5)),
                ('disconnection_time', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('charge', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('connection_time', models.CharField(max_length=5)),
                ('disconnection_time', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('charge', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('connection_time', models.CharField(max_length=5)),
                ('disconnection_time', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('charge', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('connection_time', models.CharField(max_length=5)),
                ('disconnection_time', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
    ]
